// Generated by view binder compiler. Do not edit!
package com.example.hafree.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.hafree.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityFunnyBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button english2;

  @NonNull
  public final Button iloko2;

  @NonNull
  public final Button tagalog2;

  @NonNull
  public final TextView textview2;

  private ActivityFunnyBinding(@NonNull ConstraintLayout rootView, @NonNull Button english2,
      @NonNull Button iloko2, @NonNull Button tagalog2, @NonNull TextView textview2) {
    this.rootView = rootView;
    this.english2 = english2;
    this.iloko2 = iloko2;
    this.tagalog2 = tagalog2;
    this.textview2 = textview2;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityFunnyBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityFunnyBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_funny, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityFunnyBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.english2;
      Button english2 = ViewBindings.findChildViewById(rootView, id);
      if (english2 == null) {
        break missingId;
      }

      id = R.id.iloko2;
      Button iloko2 = ViewBindings.findChildViewById(rootView, id);
      if (iloko2 == null) {
        break missingId;
      }

      id = R.id.tagalog2;
      Button tagalog2 = ViewBindings.findChildViewById(rootView, id);
      if (tagalog2 == null) {
        break missingId;
      }

      id = R.id.textview2;
      TextView textview2 = ViewBindings.findChildViewById(rootView, id);
      if (textview2 == null) {
        break missingId;
      }

      return new ActivityFunnyBinding((ConstraintLayout) rootView, english2, iloko2, tagalog2,
          textview2);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
